# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 105cb12074f134cff1181d06bbd546eed474ae1d73e01ddac2fc989ea18635a39fb6c22ed249081c83c84a0e945150e62231199fe96935082f3d9e77702af014

test:
  secret_key_base: 15211dddaffbb5dda0b6cbefb526bddc7abd4ff4bf9cc95b8d6f3029185894883aa8d3f7cf899cf202e91cf477be17b41d0cd1b4e2c69c6ea39f7a4e99bb9724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
