# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509ecbb6c3e8e7cb3c531da1b5410d3fbd6819fbc3180df95637db7a005d50adc7bca485d046cb3a48cb1748110e43a730c3c84434f6e77ec782a05fc499d138

test:
  secret_key_base: c673be0cce8195810326de47920f9b452fce4f32ddfc7ccd370ab2dc396d7cfc09296d860574b048429d57cd7a2a86492b473ad0fa56f2b79da671fde95e7b17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
